### ISSUE TITLE
fly-sass

### ISSUE THREAD

**Issue by ghost** [kashiro/fly-sass#2]
fly-sass would be better, but I am sure you already noticed the name is taken. The user squatting on the name have reached me and we are discussing what to do.

I really hope we can migrate this repo to the better name later. Thanks

**Comment by t-jindai** [comment]
@bucaran 

I replaced my repository. :+1: 
Thank you for your kindness.

https://www.npmjs.com/package/fly-sass

**Comment by ghost** [comment]
I am glad you agree this name is more user friendly! :+1: :+1:
