### ISSUE TITLE
manage include files

### ISSUE THREAD

**Issue by t-jindai** [kashiro/fly-sass#4]
# outline

`fly-sass` is transform `scss` into `css` file include helper file `( e.g. _helper.scss )`
# target
- ignore `helper` file to transform in plguin.
- or remove `helper` file after transform.

**Comment by ghost** [comment]
AFIK this is solved, check out [`examples`](https://github.com/flyjs/fly/tree/master/examples/css) in Fly. This is done via options.

``` js
export default function* () {
  yield this.clear("dist")
  yield this
    .source("src/*.scss")
    .sass({
      outputStyle: "compressed",
      includePaths: ["src/imports"],
      sourceMap: true
    })
    .target("dist")
```

Let me know if this makes sense.

**Comment by t-jindai** [comment]
@bucaran 

Sorry...
I will update in this weekend !!!!

**Comment by t-jindai** [comment]
@bucaran 

Thanks !!!
I have updated readme !
